---
- hosts: all
  become: yes
  tasks:
  - name: installing git
    apt:
      name: tree
      state: present
  - name: install wget
    apt:
      name: wget
      state: present
  - name: install webserver
    apt:
      name: apache2
      state: present
  - name: start webserver
    service:
     name: apache2
     state: started
     enabled: yes  