---
- hosts: webservers
  become: yes
  tasks: 
  - name: installing on ubuntu16
    apt:
     name: apache2
     state: present
    when: ansible_os_family =="Debian"
  - name: start server
    service: 
     name: apache2
     state: started
    when: ansible_os_family =="Debian" 

  - name: installing on redhat
    yum:
     name: httpd
     state: present
    when: ansible_os_family =="RedHat"
  - name: restart
    service:
     name: httpd
     state: started
    when: ansible_os_family =="RedHat"
