---
- name: tomuserfile
  template: 
    src: templates/tomuser.j2
    dest: /opt/tomcat/conf/tomcat-users.xml

- name: managerappfile
  template:
    src: templates/manager.j2
    dest: /opt/tomcat/webapps/manager/META-INF/context.xml

- name: hostmanagerfile
  template:
    src: templates/host.j2
    dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml